### ISSUE TITLE
Implement message viewer

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/aerc#17]
Ask on IRC for advice

**Comment by zandrmartin** [comment]
Perhaps `preview-pane=top|bottom|left|right` and `preview-pane-size=20|50%` (where 20 would be 20 cells)

**Comment by zandrmartin** [comment]
Plan to use a pty to show messages using `less`. For syntax highlighting (headers, quote levels, etc), perhaps write a small ultra-specific highlighter - `aerc-hl` maybe? - that could be used to add colors before piping, like `aerc-hl | less -R`

**Comment by SirCmpwn** [comment]
preview-pane would be nice, but let's do that in a separate issue
