### ISSUE TITLE
Support key bindings that require multiple keypresses

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/aerc#34]
i.e.

```
[lbinds]
gg = :select-message 0<Enter>
```

**Comment by eXeC64** [comment]
This should be already implemented: Just put a space between the g's. The state of the input buffer is shown in the status bar when mid way through a multi key bind.

**Comment by SirCmpwn** [comment]
`g g` should behave like `g<Space>g`. So that needs to be fixed. I would also like to change how the buffer is shown in the status bar, it should be right-aligned and use the normal status bar colors, and not overwrite the status text.

**Comment by eXeC64** [comment]
Both of those things can be refactored/resolved then as part of this issue. However, special keys may need to be enclosed in `<>` then to disambiguate `E<space>n<space>d` from `<End>`.

What do you have in mind for specific syntax? If you write some examples, I can generate some unit tests for them, and create a PR to change the behaviour.

**Comment by SirCmpwn** [comment]
>Both of those things can be refactored/resolved then as part of this issue. However, special keys may need to be enclosed in <> then to disambiguate E<space>n<space>d from <End>.

How is that? Aren't these both distinct?

    E n d = :select-message -1<Enter>

    <End> = :select-message -1<Enter>

In the former you'd press E, space, n, space, d. In the latter, you'd press the End key.

**Comment by eXeC64** [comment]
Currently `<End>` is just `End`. The `<>` wrapping is only used on the right hand side, on the left hand side each key press is currently space separated. I'll just patch it so the syntax is the same both sides. That'll cause the least confusion.

**Comment by SirCmpwn** [comment]
Cool, that sounds like a good plan.

**Comment by eXeC64** [comment]
This issue was fixed by #62
