### ISSUE TITLE
Feature request: new mail command

### ISSUE THREAD

**Issue by deathlyfrantic** [SirCmpwn/aerc#61]
I'd like the ability to specify a command to for Aerc to run when new mail is received. This would allow a user to set up notifications using their preferred notifier. Cmus has a [`status_display_program`](https://github.com/cmus/cmus/blob/master/Doc/cmus.txt#L1092-L1096) option that I think is a good model for this.

**Comment by SirCmpwn** [comment]
Why did you close this?
