### ISSUE TITLE
Having a folders filter that matches no extant folders causes infinite loop on J/K

### ISSUE THREAD

**Issue by CyanBlob** [SirCmpwn/aerc#76]
I'm trying to add multiple folders per the example in accounts.conf. I have:

```
[personal]
source=imaps://CyanBlob:password@imap.gmail.com:993
folders=Inbox,Sent
```

If I open the aerc, I see my inbox. If I try to switch to my sent folder with 'J' or ":next-folder", the program freezes and sits at 100% cpu usage, requiring me to force-kill it.
If I change "Inbox" to "INBOX", the freeze does not occur, but I still cannot access my sent folder.
I'm sure it's likely that I'm configuring something incorrectly, but this lock should be prevented.

**Comment by SirCmpwn** [comment]
What folders are displayed when you don't have a filter?

**Comment by SirCmpwn** [comment]
Additional information: your inbox is required to be named `INBOX` per the IMAP spec. I will eventually add a means of aliasing the names of folders, but for now you've gotta use `INBOX`. I think your Sent folder has a different name with GMail, and is possibly nested under some other tree. Folder names in the GMail web UI do not match the folder names in IMAP.

**Comment by CyanBlob** [comment]
With no filter, I have "INBOX" and "[Gmail] ..". The web interface shows the sent folder in the same level hierarchically as my inbox. It actually looks like GMail may be using a "sent" label instead of an actual folder. Would there still be an actual sent folder?

**Comment by SirCmpwn** [comment]
Yes, if I recall correctly it'll be under the `[Gmail]` folder. Subfolders are not supported yet, but you may be able to manually `cd` into `[Gmail]/Sent`
