### ISSUE TITLE
Connection failed: Servname not supported for ai_socktype

### ISSUE THREAD

**Issue by Immortalin** [SirCmpwn/aerc#8]
I am getting the following error when using aerc with hotmail:

```shell
Connection failed: Servname not supported for ai_socktype
```

**Comment by SirCmpwn** [comment]
Can I see your connection string? Obsfucate your password, please. Also, prepare to be underwhelmed when you do get it connected.

**Comment by Immortalin** [comment]
```
[Hotmail]
source=imaps://myemailaddress@hotmail.com[:mypassword]@imap-mail.outlook.com[:993]
```

**Comment by SirCmpwn** [comment]
You have to URL escape the @ in your username.

**Comment by Immortalin** [comment]
@SirCmpwn does this apply to passwords? Tried both, still doesn't work

**Comment by SirCmpwn** [comment]
Yep. Try something like this:

    source=imaps://myemailaddress%40hotmail.com:p%40ssword@imap-mail.outlook.com

Where your email address is myemailaddress@hotmail.com and your pw is p@ssword.

**Comment by Immortalin** [comment]
@SirCmpwn so the square brackets are optional?

**Comment by SirCmpwn** [comment]
Don't use the square brackets at all. They're just there to explain what fields are optional, the brackets themselves aren't included.

**Comment by Immortalin** [comment]
@SirCmpwn on first run, my entire Xubuntu system froze, tried switching to terminal to kill X but system did not respond, tried `REISUB` without much success, had to do a force restart, I am hesitant to try again...

**Comment by SirCmpwn** [comment]
That... does not even remotely sound like it could be aerc's fault.

**Comment by Immortalin** [comment]
@SirCmpwn thank you for your most _encouraging_ words, my system has gone through a second hard reboot now. It seems that the problem kicks in after the words `(null) -- connected` appears. What log files do you need? Should I send you an strace dump etc.?

**Comment by SirCmpwn** [comment]
I don't even know where to start. Your system is *super* fucked up if running sway could make it hard lock.

**Comment by Immortalin** [comment]
@SirCmpwn why is there sway in a terminal app?

**Comment by SirCmpwn** [comment]
I misspoke and edited my comment

**Comment by SirCmpwn** [comment]
Working on sway right now, it's on the tip of my tongue :P

**Comment by Immortalin** [comment]
@SirCmpwn I guess I will revisit aerc again in future, I need to get some work done now and I can't afford another hard lock. The OS I am currently using is an almost fresh install of Xubuntu 16.04. Apps that were running when aerc was started were Chromium and redshift
